INSERT INTO tblCountries (Id, Name, IsoCode2, IsoCode3, Capital, PhoneCode, Continent) VALUES
(1, 'Afghanistan', 'AF', 'AFG', 'Kabul', '+93', 'Asia'),
(2, 'Åland Islands', 'AX', 'ALA', 'Mariehamn', '+358', 'Europe'),
(3, 'Albania', 'AL', 'ALB', 'Tirana', '+355', 'Europe'),
(4, 'Algeria', 'DZ', 'DZA', 'Algiers', '+213', 'Africa'),
(5, 'American Samoa', 'AS', 'ASM', 'Pago Pago', '+1684', 'Oceania'),
(6, 'Andorra', 'AD', 'AND', 'Andorra la Vella', '+376', 'Europe'),
(7, 'Angola', 'AO', 'AGO', 'Luanda', '+244', 'Africa'),
(8, 'Anguilla', 'AI', 'AIA', 'The Valley', '+1264', 'North America'),
(9, 'Antarctica', 'AQ', 'ATA', NULL, NULL, 'Antarctica'),
(10, 'Antigua and Barbuda', 'AG', 'ATG', 'Saint John''s', '+1268', 'North America'),
(11, 'Argentina', 'AR', 'ARG', 'Buenos Aires', '+54', 'South America'),
(12, 'Armenia', 'AM', 'ARM', 'Yerevan', '+374', 'Asia'),
(13, 'Aruba', 'AW', 'ABW', 'Oranjestad', '+297', 'North America'),
(14, 'Australia', 'AU', 'AUS', 'Canberra', '+61', 'Oceania'),
(15, 'Austria', 'AT', 'AUT', 'Vienna', '+43', 'Europe'),
(16, 'Azerbaijan', 'AZ', 'AZE', 'Baku', '+994', 'Asia'),
(17, 'Bahamas', 'BS', 'BHS', 'Nassau', '+1242', 'North America'),
(18, 'Bahrain', 'BH', 'BHR', 'Manama', '+973', 'Asia'),
(19, 'Bangladesh', 'BD', 'BGD', 'Dhaka', '+880', 'Asia'),
(20, 'Barbados', 'BB', 'BRB', 'Bridgetown', '+1246', 'North America'),
(21, 'Belarus', 'BY', 'BLR', 'Minsk', '+375', 'Europe'),
(22, 'Belgium', 'BE', 'BEL', 'Brussels', '+32', 'Europe'),
(23, 'Belize', 'BZ', 'BLZ', 'Belmopan', '+501', 'North America'),
(24, 'Benin', 'BJ', 'BEN', 'Porto-Novo', '+229', 'Africa'),
(25, 'Bermuda', 'BM', 'BMU', 'Hamilton', '+1441', 'North America'),
(26, 'Bhutan', 'BT', 'BTN', 'Thimphu', '+975', 'Asia'),
(27, 'Bolivia', 'BO', 'BOL', 'Sucre', '+591', 'South America'),
(28, 'Bonaire, Sint Eustatius and Saba', 'BQ', 'BES', 'Kralendijk', '+599', 'North America'),
(29, 'Bosnia and Herzegovina', 'BA', 'BIH', 'Sarajevo', '+387', 'Europe'),
(30, 'Botswana', 'BW', 'BWA', 'Gaborone', '+267', 'Africa'),
(31, 'Bouvet Island', 'BV', 'BVT', NULL, '+47', 'Antarctica'),
(32, 'Brazil', 'BR', 'BRA', 'Brasília', '+55', 'South America'),
(33, 'British Indian Ocean Territory', 'IO', 'IOT', 'Diego Garcia', '+246', 'Africa'),
(34, 'British Virgin Islands', 'VG', 'VGB', 'Road Town', '+1284', 'North America'),
(35, 'Brunei', 'BN', 'BRN', 'Bandar Seri Begawan', '+673', 'Asia'),
(36, 'Bulgaria', 'BG', 'BGR', 'Sofia', '+359', 'Europe'),
(37, 'Burkina Faso', 'BF', 'BFA', 'Ouagadougou', '+226', 'Africa'),
(38, 'Burundi', 'BI', 'BDI', 'Gitega', '+257', 'Africa'),
(39, 'Cambodia', 'KH', 'KHM', 'Phnom Penh', '+855', 'Asia'),
(40, 'Cameroon', 'CM', 'CMR', 'Yaoundé', '+237', 'Africa'),
(41, 'Canada', 'CA', 'CAN', 'Ottawa', '+1', 'North America'),
(42, 'Cape Verde', 'CV', 'CPV', 'Praia', '+238', 'Africa'),
(43, 'Cayman Islands', 'KY', 'CYM', 'George Town', '+1345', 'North America'),
(44, 'Central African Republic', 'CF', 'CAF', 'Bangui', '+236', 'Africa'),
(45, 'Chad', 'TD', 'TCD', 'N''Djamena', '+235', 'Africa'),
(46, 'Chile', 'CL', 'CHL', 'Santiago', '+56', 'South America'),
(47, 'China', 'CN', 'CHN', 'Beijing', '+86', 'Asia'),
(48, 'Christmas Island', 'CX', 'CXR', 'Flying Fish Cove', '+61', 'Oceania'),
(49, 'Cocos (Keeling) Islands', 'CC', 'CCK', 'West Island', '+61', 'Oceania'),
(50, 'Colombia', 'CO', 'COL', 'Bogotá', '+57', 'South America'),
(51, 'Comoros', 'KM', 'COM', 'Moroni', '+269', 'Africa'),
(52, 'Cook Islands', 'CK', 'COK', 'Avarua', '+682', 'Oceania'),
(53, 'Costa Rica', 'CR', 'CRI', 'San José', '+506', 'North America'),
(54, 'Croatia', 'HR', 'HRV', 'Zagreb', '+385', 'Europe'),
(55, 'Cuba', 'CU', 'CUB', 'Havana', '+53', 'North America'),
(56, 'Curaçao', 'CW', 'CUW', 'Willemstad', '+599', 'North America'),
(57, 'Cyprus', 'CY', 'CYP', 'Nicosia', '+357', 'Europe'),
(58, 'Czechia', 'CZ', 'CZE', 'Prague', '+420', 'Europe'),
(59, 'Denmark', 'DK', 'DNK', 'Copenhagen', '+45', 'Europe'),
(60, 'Djibouti', 'DJ', 'DJI', 'Djibouti', '+253', 'Africa'),
(61, 'Dominica', 'DM', 'DMA', 'Roseau', '+1767', 'North America'),
(62, 'Dominican Republic', 'DO', 'DOM', 'Santo Domingo', '+1', 'North America'),
(63, 'DR Congo', 'CD', 'COD', 'Kinshasa', '+243', 'Africa'),
(64, 'Ecuador', 'EC', 'ECU', 'Quito', '+593', 'South America'),
(65, 'Egypt', 'EG', 'EGY', 'Cairo', '+20', 'Africa'),
(66, 'El Salvador', 'SV', 'SLV', 'San Salvador', '+503', 'North America'),
(67, 'Equatorial Guinea', 'GQ', 'GNQ', 'Malabo', '+240', 'Africa'),
(68, 'Eritrea', 'ER', 'ERI', 'Asmara', '+291', 'Africa'),
(69, 'Estonia', 'EE', 'EST', 'Tallinn', '+372', 'Europe'),
(70, 'Eswatini', 'SZ', 'SWZ', 'Mbabane', '+268', 'Africa'),
(71, 'Ethiopia', 'ET', 'ETH', 'Addis Ababa', '+251', 'Africa'),
(72, 'Falkland Islands', 'FK', 'FLK', 'Stanley', '+500', 'South America'),
(73, 'Faroe Islands', 'FO', 'FRO', 'Tórshavn', '+298', 'Europe'),
(74, 'Fiji', 'FJ', 'FJI', 'Suva', '+679', 'Oceania'),
(75, 'Finland', 'FI', 'FIN', 'Helsinki', '+358', 'Europe'),
(76, 'France', 'FR', 'FRA', 'Paris', '+33', 'Europe'),
(77, 'French Guiana', 'GF', 'GUF', 'Cayenne', '+594', 'South America'),
(78, 'French Polynesia', 'PF', 'PYF', 'Papeetē', '+689', 'Oceania'),
(79, 'French Southern and Antarctic Lands', 'TF', 'ATF', 'Port-aux-Français', '+262', 'Antarctica'),
(80, 'Gabon', 'GA', 'GAB', 'Libreville', '+241', 'Africa'),
(81, 'Gambia', 'GM', 'GMB', 'Banjul', '+220', 'Africa'),
(82, 'Georgia', 'GE', 'GEO', 'Tbilisi', '+995', 'Asia'),
(83, 'Germany', 'DE', 'DEU', 'Berlin', '+49', 'Europe'),
(84, 'Ghana', 'GH', 'GHA', 'Accra', '+233', 'Africa'),
(85, 'Gibraltar', 'GI', 'GIB', 'Gibraltar', '+350', 'Europe'),
(86, 'Greece', 'GR', 'GRC', 'Athens', '+30', 'Europe'),
(87, 'Greenland', 'GL', 'GRL', 'Nuuk', '+299', 'North America'),
(88, 'Grenada', 'GD', 'GRD', 'St. George''s', '+1473', 'North America'),
(89, 'Guadeloupe', 'GP', 'GLP', 'Basse-Terre', '+590', 'North America'),
(90, 'Guam', 'GU', 'GUM', 'Hagåtña', '+1671', 'Oceania'),
(91, 'Guatemala', 'GT', 'GTM', 'Guatemala City', '+502', 'North America'),
(92, 'Guernsey', 'GG', 'GGY', 'St. Peter Port', '+44', 'Europe'),
(93, 'Guinea', 'GN', 'GIN', 'Conakry', '+224', 'Africa'),
(94, 'Guinea-Bissau', 'GW', 'GNB', 'Bissau', '+245', 'Africa'),
(95, 'Guyana', 'GY', 'GUY', 'Georgetown', '+592', 'South America'),
(96, 'Haiti', 'HT', 'HTI', 'Port-au-Prince', '+509', 'North America'),
(97, 'Heard Island and McDonald Islands', 'HM', 'HMD', NULL, NULL, 'Antarctica'),
(98, 'Honduras', 'HN', 'HND', 'Tegucigalpa', '+504', 'North America'),
(99, 'Hong Kong', 'HK', 'HKG', 'City of Victoria', '+852', 'Asia'),
(100, 'Hungary', 'HU', 'HUN', 'Budapest', '+36', 'Europe'),
(101, 'Iceland', 'IS', 'ISL', 'Reykjavik', '+354', 'Europe'),
(102, 'India', 'IN', 'IND', 'New Delhi', '+91', 'Asia'),
(103, 'Indonesia', 'ID', 'IDN', 'Jakarta', '+62', 'Asia'),
(104, 'Iran', 'IR', 'IRN', 'Tehran', '+98', 'Asia'),
(105, 'Iraq', 'IQ', 'IRQ', 'Baghdad', '+964', 'Asia'),
(106, 'Ireland', 'IE', 'IRL', 'Dublin', '+353', 'Europe'),
(107, 'Isle of Man', 'IM', 'IMN', 'Douglas', '+44', 'Europe'),
(108, 'Israel', 'IL', 'ISR', 'Jerusalem', '+972', 'Asia'),
(109, 'Italy', 'IT', 'ITA', 'Rome', '+39', 'Europe'),
(110, 'Ivory Coast', 'CI', 'CIV', 'Yamoussoukro', '+225', 'Africa'),
(111, 'Jamaica', 'JM', 'JAM', 'Kingston', '+1876', 'North America'),
(112, 'Japan', 'JP', 'JPN', 'Tokyo', '+81', 'Asia'),
(113, 'Jersey', 'JE', 'JEY', 'Saint Helier', '+44', 'Europe'),
(114, 'Jordan', 'JO', 'JOR', 'Amman', '+962', 'Asia'),
(115, 'Kazakhstan', 'KZ', 'KAZ', 'Nur-Sultan', '+7', 'Asia'),
(116, 'Kenya', 'KE', 'KEN', 'Nairobi', '+254', 'Africa'),
(117, 'Kiribati', 'KI', 'KIR', 'South Tarawa', '+686', 'Oceania'),
(118, 'Kosovo', 'XK', 'XKX', 'Pristina', '+383', 'Europe'),
(119, 'Kuwait', 'KW', 'KWT', 'Kuwait City', '+965', 'Asia'),
(120, 'Kyrgyzstan', 'KG', 'KGZ', 'Bishkek', '+996', 'Asia'),
(121, 'Laos', 'LA', 'LAO', 'Vientiane', '+856', 'Asia'),
(122, 'Latvia', 'LV', 'LVA', 'Riga', '+371', 'Europe'),
(123, 'Lebanon', 'LB', 'LBN', 'Beirut', '+961', 'Asia'),
(124, 'Lesotho', 'LS', 'LSO', 'Maseru', '+266', 'Africa'),
(125, 'Liberia', 'LR', 'LBR', 'Monrovia', '+231', 'Africa'),
(126, 'Libya', 'LY', 'LBY', 'Tripoli', '+218', 'Africa'),
(127, 'Liechtenstein', 'LI', 'LIE', 'Vaduz', '+423', 'Europe'),
(128, 'Lithuania', 'LT', 'LTU', 'Vilnius', '+370', 'Europe'),
(129, 'Luxembourg', 'LU', 'LUX', 'Luxembourg', '+352', 'Europe'),
(130, 'Macau', 'MO', 'MAC', NULL, '+853', 'Asia'),
(131, 'Madagascar', 'MG', 'MDG', 'Antananarivo', '+261', 'Africa'),
(132, 'Malawi', 'MW', 'MWI', 'Lilongwe', '+265', 'Africa'),
(133, 'Malaysia', 'MY', 'MYS', 'Kuala Lumpur', '+60', 'Asia'),
(134, 'Maldives', 'MV', 'MDV', 'Malé', '+960', 'Asia'),
(135, 'Mali', 'ML', 'MLI', 'Bamako', '+223', 'Africa'),
(136, 'Malta', 'MT', 'MLT', 'Valletta', '+356', 'Europe'),
(137, 'Marshall Islands', 'MH', 'MHL', 'Majuro', '+692', 'Oceania'),
(138, 'Martinique', 'MQ', 'MTQ', 'Fort-de-France', '+596', 'North America'),
(139, 'Mauritania', 'MR', 'MRT', 'Nouakchott', '+222', 'Africa'),
(140, 'Mauritius', 'MU', 'MUS', 'Port Louis', '+230', 'Africa'),
(141, 'Mayotte', 'YT', 'MYT', 'Mamoudzou', '+262', 'Africa'),
(142, 'Mexico', 'MX', 'MEX', 'Mexico City', '+52', 'North America'),
(143, 'Micronesia', 'FM', 'FSM', 'Palikir', '+691', 'Oceania'),
(144, 'Moldova', 'MD', 'MDA', 'Chișinău', '+373', 'Europe'),
(145, 'Monaco', 'MC', 'MCO', 'Monaco', '+377', 'Europe'),
(146, 'Mongolia', 'MN', 'MNG', 'Ulan Bator', '+976', 'Asia'),
(147, 'Montenegro', 'ME', 'MNE', 'Podgorica', '+382', 'Europe'),
(148, 'Montserrat', 'MS', 'MSR', 'Plymouth', '+1664', 'North America'),
(149, 'Morocco', 'MA', 'MAR', 'Rabat', '+212', 'Africa'),
(150, 'Mozambique', 'MZ', 'MOZ', 'Maputo', '+258', 'Africa'),
(151, 'Myanmar', 'MM', 'MMR', 'Naypyidaw', '+95', 'Asia'),
(152, 'Namibia', 'NA', 'NAM', 'Windhoek', '+264', 'Africa'),
(153, 'Nauru', 'NR', 'NRU', 'Yaren', '+674', 'Oceania'),
(154, 'Nepal', 'NP', 'NPL', 'Kathmandu', '+977', 'Asia'),
(155, 'Netherlands', 'NL', 'NLD', 'Amsterdam', '+31', 'Europe'),
(156, 'New Caledonia', 'NC', 'NCL', 'Nouméa', '+687', 'Oceania'),
(157, 'New Zealand', 'NZ', 'NZL', 'Wellington', '+64', 'Oceania'),
(158, 'Nicaragua', 'NI', 'NIC', 'Managua', '+505', 'North America'),
(159, 'Niger', 'NE', 'NER', 'Niamey', '+227', 'Africa'),
(160, 'Nigeria', 'NG', 'NGA', 'Abuja', '+234', 'Africa'),
(161, 'Niue', 'NU', 'NIU', 'Alofi', '+683', 'Oceania'),
(162, 'Norfolk Island', 'NF', 'NFK', 'Kingston', '+672', 'Oceania'),
(163, 'North Korea', 'KP', 'PRK', 'Pyongyang', '+850', 'Asia'),
(164, 'North Macedonia', 'MK', 'MKD', 'Skopje', '+389', 'Europe'),
(165, 'Northern Mariana Islands', 'MP', 'MNP', 'Saipan', '+1670', 'Oceania'),
(166, 'Norway', 'NO', 'NOR', 'Oslo', '+47', 'Europe'),
(167, 'Oman', 'OM', 'OMN', 'Muscat', '+968', 'Asia'),
(168, 'Pakistan', 'PK', 'PAK', 'Islamabad', '+92', 'Asia'),
(169, 'Palau', 'PW', 'PLW', 'Ngerulmud', '+680', 'Oceania'),
(170, 'Palestine', 'PS', 'PSE', 'Ramallah', '+970', 'Asia'),
(171, 'Panama', 'PA', 'PAN', 'Panama City', '+507', 'North America'),
(172, 'Papua New Guinea', 'PG', 'PNG', 'Port Moresby', '+675', 'Oceania'),
(173, 'Paraguay', 'PY', 'PRY', 'Asunción', '+595', 'South America'),
(174, 'Peru', 'PE', 'PER', 'Lima', '+51', 'South America'),
(175, 'Philippines', 'PH', 'PHL', 'Manila', '+63', 'Asia'),
(176, 'Pitcairn Islands', 'PN', 'PCN', 'Adamstown', '+64', 'Oceania'),
(177, 'Poland', 'PL', 'POL', 'Warsaw', '+48', 'Europe'),
(178, 'Portugal', 'PT', 'PRT', 'Lisbon', '+351', 'Europe'),
(179, 'Puerto Rico', 'PR', 'PRI', 'San Juan', '+1', 'North America'),
(180, 'Qatar', 'QA', 'QAT', 'Doha', '+974', 'Asia'),
(181, 'Republic of the Congo', 'CG', 'COG', 'Brazzaville', '+242', 'Africa'),
(182, 'Réunion', 'RE', 'REU', 'Saint-Denis', '+262', 'Africa'),
(183, 'Romania', 'RO', 'ROU', 'Bucharest', '+40', 'Europe'),
(184, 'Russia', 'RU', 'RUS', 'Moscow', '+7', 'Europe'),
(185, 'Rwanda', 'RW', 'RWA', 'Kigali', '+250', 'Africa'),
(186, 'Saint Barthélemy', 'BL', 'BLM', 'Gustavia', '+590', 'North America'),
(187, 'Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', 'Jamestown', '+290', 'Africa'),
(188, 'Saint Kitts and Nevis', 'KN', 'KNA', 'Basseterre', '+1869', 'North America'),
(189, 'Saint Lucia', 'LC', 'LCA', 'Castries', '+1758', 'North America'),
(190, 'Saint Martin', 'MF', 'MAF', 'Marigot', '+590', 'North America'),
(191, 'Saint Pierre and Miquelon', 'PM', 'SPM', 'Saint-Pierre', '+508', 'North America'),
(192, 'Saint Vincent and the Grenadines', 'VC', 'VCT', 'Kingstown', '+1784', 'North America'),
(193, 'Samoa', 'WS', 'WSM', 'Apia', '+685', 'Oceania'),
(194, 'San Marino', 'SM', 'SMR', 'City of San Marino', '+378', 'Europe'),
(195, 'São Tomé and Príncipe', 'ST', 'STP', 'São Tomé', '+239', 'Africa'),
(196, 'Saudi Arabia', 'SA', 'SAU', 'Riyadh', '+966', 'Asia'),
(197, 'Senegal', 'SN', 'SEN', 'Dakar', '+221', 'Africa'),
(198, 'Serbia', 'RS', 'SRB', 'Belgrade', '+381', 'Europe'),
(199, 'Seychelles', 'SC', 'SYC', 'Victoria', '+248', 'Africa'),
(200, 'Sierra Leone', 'SL', 'SLE', 'Freetown', '+232', 'Africa'),
(201, 'Singapore', 'SG', 'SGP', 'Singapore', '+65', 'Asia'),
(202, 'Sint Maarten', 'SX', 'SXM', 'Philipsburg', '+1721', 'North America'),
(203, 'Slovakia', 'SK', 'SVK', 'Bratislava', '+421', 'Europe'),
(204, 'Slovenia', 'SI', 'SVN', 'Ljubljana', '+386', 'Europe'),
(205, 'Solomon Islands', 'SB', 'SLB', 'Honiara', '+677', 'Oceania'),
(206, 'Somalia', 'SO', 'SOM', 'Mogadishu', '+252', 'Africa'),
(207, 'South Africa', 'ZA', 'ZAF', 'Pretoria', '+27', 'Africa'),
(208, 'South Georgia', 'GS', 'SGS', 'King Edward Point', '+500', 'Antarctica'),
(209, 'South Korea', 'KR', 'KOR', 'Seoul', '+82', 'Asia'),
(210, 'South Sudan', 'SS', 'SSD', 'Juba', '+211', 'Africa'),
(211, 'Spain', 'ES', 'ESP', 'Madrid', '+34', 'Europe'),
(212, 'Sri Lanka', 'LK', 'LKA', 'Sri Jayawardenepura Kotte', '+94', 'Asia'),
(213, 'Sudan', 'SD', 'SDN', 'Khartoum', '+249', 'Africa'),
(214, 'Suriname', 'SR', 'SUR', 'Paramaribo', '+597', 'South America'),
(215, 'Svalbard and Jan Mayen', 'SJ', 'SJM', 'Longyearbyen', '+47', 'Europe'),
(216, 'Sweden', 'SE', 'SWE', 'Stockholm', '+46', 'Europe'),
(217, 'Switzerland', 'CH', 'CHE', 'Bern', '+41', 'Europe'),
(218, 'Syria', 'SY', 'SYR', 'Damascus', '+963', 'Asia'),
(219, 'Taiwan', 'TW', 'TWN', 'Taipei', '+886', 'Asia'),
(220, 'Tajikistan', 'TJ', 'TJK', 'Dushanbe', '+992', 'Asia'),
(221, 'Tanzania', 'TZ', 'TZA', 'Dodoma', '+255', 'Africa'),
(222, 'Thailand', 'TH', 'THA', 'Bangkok', '+66', 'Asia'),
(223, 'Timor-Leste', 'TL', 'TLS', 'Dili', '+670', 'Oceania'),
(224, 'Togo', 'TG', 'TGO', 'Lomé', '+228', 'Africa'),
(225, 'Tokelau', 'TK', 'TKL', 'Fakaofo', '+690', 'Oceania'),
(226, 'Tonga', 'TO', 'TON', 'Nuku''alofa', '+676', 'Oceania'),
(227, 'Trinidad and Tobago', 'TT', 'TTO', 'Port of Spain', '+1868', 'North America'),
(228, 'Tunisia', 'TN', 'TUN', 'Tunis', '+216', 'Africa'),
(229, 'Turkey', 'TR', 'TUR', 'Ankara', '+90', 'Asia'),
(230, 'Turkmenistan', 'TM', 'TKM', 'Ashgabat', '+993', 'Asia'),
(231, 'Turks and Caicos Islands', 'TC', 'TCA', 'Cockburn Town', '+1649', 'North America'),
(232, 'Tuvalu', 'TV', 'TUV', 'Funafuti', '+688', 'Oceania'),
(233, 'Uganda', 'UG', 'UGA', 'Kampala', '+256', 'Africa'),
(234, 'Ukraine', 'UA', 'UKR', 'Kyiv', '+380', 'Europe'),
(235, 'United Arab Emirates', 'AE', 'ARE', 'Abu Dhabi', '+971', 'Asia'),
(236, 'United Kingdom', 'GB', 'GBR', 'London', '+44', 'Europe'),
(237, 'United States', 'US', 'USA', 'Washington, D.C.', '+1', 'North America'),
(238, 'United States Minor Outlying Islands', 'UM', 'UMI', 'Washington DC', '+1', 'North America'),
(239, 'United States Virgin Islands', 'VI', 'VIR', 'Charlotte Amalie', '+1340', 'North America'),
(240, 'Uruguay', 'UY', 'URY', 'Montevideo', '+598', 'South America'),
(241, 'Uzbekistan', 'UZ', 'UZB', 'Tashkent', '+998', 'Asia'),
(242, 'Vanuatu', 'VU', 'VUT', 'Port Vila', '+678', 'Oceania'),
(243, 'Vatican City', 'VA', 'VAT', 'Vatican City', '+379', 'Europe'),
(44, 'Venezuela', 'VE', 'VEN', 'Caracas', '+58', 'South America'),
(245, 'Vietnam', 'VN', 'VNM', 'Hanoi', '+84', 'Asia'),
(246, 'Wallis and Futuna', 'WF', 'WLF', 'Mata-Utu', '+681', 'Oceania'),
(247, 'Western Sahara', 'EH', 'ESH', 'El Aaiún', '+212', 'Africa'),
(248, 'Yemen', 'YE', 'YEM', 'Sana''a', '+967', 'Asia'),
(249, 'Zambia', 'ZM', 'ZMB', 'Lusaka', '+260', 'Africa'),
(250, 'Zimbabwe', 'ZW', 'ZWE', 'Harare', '+263', 'Africa')
ON DUPLICATE KEY UPDATE
    Name = VALUES(Name),
    IsoCode2 = VALUES(IsoCode2),
    IsoCode3 = VALUES(IsoCode3),
    Capital = VALUES(Capital),
    PhoneCode = VALUES(PhoneCode),
    Continent = VALUES(Continent);
